on:
  push:
    branches: [ "main" ]
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@2.26.0
      with:
        php-version: '8.2.4'
    - uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate

    - name: Migration
      run: php artisan migrate:fresh --seed --force

    - name: Permissions assign Setup
      run: php artisan assign:permission --force

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    # - name: Config Clearing
    #   run: php artisan config:clear

    # - name: Cache Clearing
    #   run: php artisan cache:clear

    # - name: Generate App Key
    #   run: php artisan key:generate

    - name: Install Npm
      run: npm install

    - name: Compile Css and Js Assets
      run: npm run build

    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    # - name: Create Database
    #   run: |
    #     mkdir -p database
    #     touch database/database.mysql

      env:
        DB_CONNECTION: mysql
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /public_html/