on: 
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: composer install --prefer-dist --no-interaction
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: dev.yowza.co.za
        username: devyodgpja
        password: fvA0KV8FksSuTI9rT0fv
        server-dir: /public_html/dev/